CHWMBC: Test corrections
BettercareHealth/bettercare pull request #91
Opened 2017-03-02 20:10 UTC by nkoeries

2017-03-09 05:25 UTC, arthurattwell requested changes
@nkoeries I've left a few comments/requests for changes here. Can you make these and let me know when you have?

2017-03-09 05:25 UTC, arthurattwell commented on primary-maternal-care/1.md
> +quiz-id: 90
@nkoeries Checking why this has changed. Did you figure out how to update the online tests? I'm impressed if you did, we hadn't got to that training yet :) Even then, the fact that this is an older test ID than the original (131) suggests you didn't create a new text but are using an old one. Can you fill me in on why you made this change?

2017-03-09 05:25 UTC, arthurattwell commented on primary-maternal-care/1B.md
> +title: 1. Antenatal care
@nkoeries This looks like an old Skills chapter (1B) has been replaced with one of the updated chapters taken from Maternal Care (chapter 1). Was this a mistake or am I missing something?

2017-03-09 05:25 UTC, arthurattwell commented on primary-maternal-care/2.md
> +quiz-id: 91
@nkoeries I think I've figured this out: these are the quiz IDs for Maternal Care? We must create new quizzes and not reuse the MC ones -- at at worst stick to told IDs (132 in this case). I'll have to show you how to do that. There should be basic info on the wiki.

The IDs refer to specific quizzes on quiz.bettercare.co.za, where we manage our online-quiz database.

2017-03-09 05:25 UTC, arthurattwell commented on primary-maternal-care/3.md
> +quiz-id: 92
@nkoeries Again, here we must stick to 133 until we create new quizzes for PMC.

2017-03-09 05:25 UTC, arthurattwell commented on primary-maternal-care/4.md
> +quiz-id: 93
@nkoeries Again, stick to 134 here till we have new tests for PMC.

2017-03-09 05:25 UTC, arthurattwell commented on primary-maternal-care/5.md
> +quiz-id: 94
@nkoeries Again, stick to 135 here till we have new tests for PMC.

2017-03-09 05:25 UTC, arthurattwell commented on primary-maternal-care/7.md
> +title: . Medical problems during pregnancy, labour and the puerperium
@nkoeries Please add back the chapter number before the full stop at the start of the title here.

2017-03-09 05:25 UTC, arthurattwell commented on primary-maternal-care/7.md
> +quiz-id: 102
@nkoeries Again, stick to 137 here till we have new tests for PMC.

2017-03-09 05:25 UTC, arthurattwell commented on primary-maternal-care/7.md
> +title: . Medical problems during pregnancy, labour and the puerperium
@nkoeries Is there a chapter 6? I don't see one in the PR here.

2017-03-09 06:01 UTC, nkoeries commented on primary-maternal-care/7.md
> +title: . Medical problems during pregnancy, labour and the puerperium
The chapter 6 is there but it remains as is. Gerhard has made no changes to it.

2017-03-09 06:01 UTC, nkoeries commented on primary-maternal-care/2.md
> +quiz-id: 91
Got it. Will review Wiki again to get this right.

2017-03-09 06:01 UTC, nkoeries commented on primary-maternal-care/1.md
> +quiz-id: 90
I have not figured out how to change the online tests. What has happened is that Gerhard and Dave have updated the PMC chapters with the new MC. I began migrating the content including the test changes (clearing I was jumping the gun).

2017-03-09 06:02 UTC, nkoeries commented on primary-maternal-care/3.md
> +quiz-id: 92
@arthurattwell noted. I will make the changes.

2017-03-09 06:02 UTC, nkoeries commented on primary-maternal-care/4.md
> +quiz-id: 93
@arthurattwell noted. I will make the changes.

2017-03-09 06:02 UTC, nkoeries commented on primary-maternal-care/7.md
> +quiz-id: 102
@arthurattwell noted. I will make the changes.

2017-03-09 06:04 UTC, nkoeries commented on primary-maternal-care/7.md
> +title: . Medical problems during pregnancy, labour and the puerperium
@arthurattwell Chapter number added back.

2017-03-09 06:05 UTC, nkoeries commented on primary-maternal-care/1B.md
> +title: 1. Antenatal care
@arthurattwell The content from Maternal Care replaces older material from Primary Maternal Care.

2017-03-09 06:08 UTC, nkoeries commented on primary-maternal-care/1.md
> +quiz-id: 90
@arthurattwell I will revert all the test IDs bearing in mind that the content has been changed.

2017-03-10 13:11 UTC, arthurattwell commented on primary-maternal-care/1B.md
> +title: 1. Antenatal care
@nkoeries What I mean is that you seem to have pasted the content for chapter 1 over Skills chapter 1B here.

2017-03-10 13:27 UTC, nkoeries commented on primary-maternal-care/1B.md
> +title: 1. Antenatal care
@arthurattwell I see my mistake. I've corrected it. Trying to sync it now.

2017-03-10 13:50 UTC, arthurattwell approved these changes

2017-03-10 14:20 UTC, merged